[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
lisk-sepolia = "${RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config