[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true

[rpc_endpoints]
lis-sepolia = "${RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config